Dev
annam23/PythonPY110-exam pull request #1
Opened 2021-12-17 15:28 UTC by annam23

Зачетное задание по курсу PythonPY110
Машунина Анна Анатольевна

2021-12-19 18:03 UTC, EnotYoyo requested changes
Жду правок по замечаниям.

2021-12-19 18:03 UTC, EnotYoyo commented on main.py
> +def main():
Не хватает документации для функции.

2021-12-19 18:03 UTC, EnotYoyo commented on main.py
> +        with open('books_dict_json.txt', 'w', encoding='utf-8') as result_file:
Этот блок кода нужно вынести из под цикла, поскольку он выполняется на каждой итерации цикла, а должен всего лишь один раз, когда список окончательно сформирован.

2021-12-19 18:03 UTC, EnotYoyo commented on main.py
> +def gen_function(pk=1) -> dict:
В этой функции у Вас есть одна очень неочевидная проблема.  

У Вас на каждой итерации цикла возвращается один и тот же  словарь. получается, что изменяя один словарь Вы изменяете все сохраненные словари до этого. Можете в этом убедиться, посмотрев в файл json - там будут одинаковые словари. 

Чтобы избежать эту проблему, нужно создание словаря делать в цикле, где и заполняются поля.

2021-12-19 18:03 UTC, EnotYoyo commented on main.py
> +    year = random.randint(1997, 2008)
Обычно такое сокращают до `return random.randint(1997, 2008)`. Поскольку это короче, но при этом так же выразительно, как и через переменную.

2021-12-19 18:03 UTC, EnotYoyo commented on main.py
> +    rating = random.uniform(0, 5)
Рейтинг и цену лучше окрглять, а то слишком много знаков после запятой :)

2021-12-19 19:17 UTC, annam23 commented
> 

Сделала все исправления, теперь в json записываются разные словари.

2021-12-19 19:17 UTC, annam23 commented on main.py
> +    rating = random.uniform(0, 5)
+

2021-12-19 19:17 UTC, annam23 commented on main.py
> +    year = random.randint(1997, 2008)
спасибо!

2021-12-19 19:17 UTC, annam23 commented on main.py
> +def gen_function(pk=1) -> dict:
поняла, цикл добавила

2021-12-19 19:18 UTC, annam23 commented on main.py
> +def main():
+

2021-12-19 19:18 UTC, annam23 commented on main.py
> +        with open('books_dict_json.txt', 'w', encoding='utf-8') as result_file:
готово

2021-12-20 08:20 UTC, EnotYoyo requested changes
Помимо замечаний так и не увидел документацию :(

2021-12-20 08:20 UTC, EnotYoyo commented on main.py
> +def gen_function(how_many_dict, pk=1) -> dict:
how_many_dict - хорошо бы сделать int-ом, а range для итерации уже делать внутри генератора.

2021-12-20 08:20 UTC, EnotYoyo commented on main.py
> +    fake = Faker()
И что по поводу выноса этого объекта в глобальную область видимости?

2021-12-20 14:54 UTC, annam23 commented
Не сразу поняла про документацию, дополнила main описанием.
Плюс скорректировала range и fake вынесла!

2021-12-21 12:23 UTC, EnotYoyo approved these changes
Документацию нужно было ко всем функциям и модулю :) 

Принято, зачет.

2021-12-21 12:23 UTC, EnotYoyo commented on main.py
> +def main() -> json:
Эта функция ничего не возвращает :)

2021-12-21 12:23 UTC, EnotYoyo commented on main.py
> +def gen_function(how_many_dict: int, pk=1) -> dict:
`-> Iterable[dict]` - поскольку функция возвращает что-то итерируемое (генератор). Можно воспользловаться и тайпингом генератора.

2021-12-21 12:23 UTC, EnotYoyo commented on main.py
> +    Faker.seed(0)
seed - это начальное значение для рандома. Смотрите, допустим Вы пишете тесты для тестирования Вашего кода. И Вы хотите, чтобы значения в тестах были воспроизводимы. То есть "случайные" значения были одинаковыми при каждом запуске тестов. Вот такого эффекта можно добиться задавая значения seed.  

Вот [пример](https://ru.wikipedia.org/wiki/%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D0%BD%D0%B3%D1%80%D1%83%D1%8D%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4) генерации псевдослучайных значений. В нем seed'ом является X0. 

Т.о. Вам не нужно вызывать этот метод каждый раз при вызове функции. Можно вызвать один раз в глобальной области видимости или вообще не трогать.

2022-04-03 10:18 UTC, merged